name: Run Tests

on:
  push:

jobs:
  lint:
    name: Run automated tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Bun to run lint
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run tests
        env:
          BUN_OPTIONS: '--tsconfig-override=tsconfig.test.ts'
        run: bun test
